name: email-test
on:
    schedule:
        - cron: '0 0 1 1 *'
jobs:
    cron:
        runs-on: ubuntu-latest
        steps:
            - name: Call our API route Test
              run: |
                  curl --request POST --url "https://mmp3.vercel.app/api/cron" --header "Authorization: Bearer ${{ secrets.API_SECRET_KEY }}"
