name: notificationsClearing
on:
    schedule:
        - cron: '0 * * * *'
jobs:
    cron:
        runs-on: ubuntu-latest
        steps:
            - name: Notifications Clearing Cron Job
              run: |
                  curl --request POST --url "https://mmp3.vercel.app/api/cron/notificationsClearing" --header "Authorization: Bearer ${{ secrets.API_SECRET_KEY }}"